### PR TITLE
fix to comply with latest version gcalcli

### PR DESCRIPTION
**Pull request by Bryntet**
It is currently broken and this fixes it :)

### CODE REVIEW

**Comment by chmouel** [comment]
really ? which version of gcalcli ? I use 4.3.0 (from arch i think)

**Comment by chmouel** [comment]
looks like your PR is working as well for me, so if it fixes things for you i am happy to merge this :) 

let me know if you need a release..

**Comment by Bryntet** [comment]
installed via AUR and nothing showed up in the meeting notes

`gcalcli --nocolor agenda --nodeclined --calendar=My\ calendar --details=end --details=url --tsv today` gives `gcalcli agenda: error: argument start: invalid get_time_from_str value: '--calendar=My calendar'`

whereas `gcalcli --nocolor --calendar=Automated\ school\ calendar agenda today --nodeclined --details=end --details=url --tsv` works

you can do a release if you'd like, as I first just shrugged this off as your project not working, since your program doesn't give the user the gcalcli error message

**Comment by chmouel** [comment]
ah sounds good thanks, it's weird that i have the same version  and it works for me,

i'll see if i can output the gcalcli error from now on, 

thanks again for the fix, it should be release in the AUR now

**Pull request merged**
